#!/usr/bin/python

import os

for filename in os.listdir(os.getcwd()):
    namebase = filename.rstrip('docsxwodtrtf')
    namebase = namebase.lower()
    namebase = namebase.replace(' ', '-')
    namebase = namebase.replace('--', '-')
    name = namebase + 'markdown'
    print filename
    filename = filename.replace(' ', '\ ')
    if filename[-3:] == 'doc' or filename[-3:] == 'rtf':
        print filename
        os.system('catdoc '+filename+'>> '+ name)
    elif filename[-3:] == 'sxw' or filename[-3:] == 'odt':
        os.system('odt2txt '+filename+'>> '+ name)
