#!/usr/bin/python

import os, glob, yaml

mkdowns = glob.glob('*.markdown')

index = open('index.markdown', 'a')

index.write('\n\n')

for flname in mkdowns:
    if flname == 'index.markdown':
        continue
    fl = open(flname)
    fl_yaml = yaml.load_all(fl).next()
    print fl_yaml
    link_text = fl_yaml['title']
    link_loc = flname.strip('markdown') + "html"
    try:
        link_desc = fl_yaml['description']
    except KeyError:
        link_desc = ""
    link_line = "+ " + "[" + link_text + "]" + "(" + link_loc + ")" + "  " + link_desc + '\n'
    index.write(link_line)

index.close()    
