#!/usr/bin/python

import os, glob
from pybtex.database.input import bibtex

def format_authors(auth):
    authors = auth.split(' and ')
    formatted = []
    for author in authors:
        if author.find(',') == -1:
            formatted.append(author)
        else:
            names = author.count(',')
            parts = author.split(',')
            name = author
            if names == 1:
                name = parts[1].strip() + ' ' + parts[0].strip()
            elif names == 2:
                name = parts[2].strip() + ' ' + parts[0].strip() + ' ' + parts[1].strip()
            formatted.append(name)
    return formatted


#### Constants ####
note_names = glob.glob('notes/*')
papers = glob.glob('papers/*')

paper_path = 'papers/'
note_path = 'notes/'

paper_ext = '.pdf'
note_ext = '.org'

cite_file = 'papers/citations.bib'

details = 'y'

header = '* '
bullet = '  + '

paper_names = []

for fl in papers:
    if not fl.find(paper_ext) == -1:
        paper_names.append(fl.replace(paper_ext,'').replace(paper_path, ''))

parser = bibtex.Parser()
bib_data = parser.parse_file(cite_file)

summary = open('summary', 'w')

for paper in paper_names:
    paper_data = bib_data.entries[paper]
    try:
        title = paper_data.fields['title']
        link = paper_path + paper + paper_ext
        entry = header + '[[./' + link + '][' + title +']]'
        try:
            note_index = note_names.index(note_path + paper + note_ext)
            note = '[[./' + note_names[note_index] + '][Notes]]'
            summary.write(entry)
            summary.write(' -> ')
            summary.write(note + '\n')
        except Exception as err:
            print "No note found for", err
            summary.write(entry + '\n')

        if details == 'y':
            authors = paper_data.fields['author']
            authors = format_authors(authors)
            authors = bullet + ' and '.join(authors)

            try:
                published = bullet + paper_data.fields['journal']
            except:
                published = bullet + paper_data.fields['booktitle']

            year = bullet + paper_data.fields['year']
            
            summary.write(authors + '\n')
            summary.write(published + '\n')
            summary.write(year + '\n')
            
    except Exception as err:
        print "An error occured while processing: ", paper
        print err

summary.close()


