#!/usr/bin/python

import os, glob
from pybtex.database.input import bibtex

def format_authors(auth):
    authors = auth.split(' and ')
    formatted = []
    for author in authors:
        if author.find(',') == -1:
            formatted.append(author)
        else:
            names = author.count(',')
            parts = author.split(',')
            name = author
            if names == 1:
                name = parts[1].strip() + ' ' + parts[0].strip()
            elif names == 2:
                name = parts[2].strip() + ' ' + parts[0].strip() + ' ' + parts[1].strip()
            formatted.append(name)
    return formatted


note_names = glob.glob('notes/*')
pdf_names = glob.glob('papers/*')
details = 'y'
print note_names
paper_names = []

for fl in pdf_names:
    if fl[-3:] == 'pdf':
        print fl
        paper_names.append(fl.replace('.pdf','').replace('papers/', ''))

parser = bibtex.Parser()
bib_data = parser.parse_file('papers/citations.bib')

wiki = open('wiki', 'w')

for paper in paper_names:
    try:
        title = bib_data.entries[paper].fields['title']
        link = './papers/' + paper + '.pdf'
        entry = '* ' + '[[' + link + '][' + title +']]'
        try:
            note_index = note_names.index('notes/' + paper + '.org')
            note = '[[./' + note_names[note_index] + '][Notes]]'
            wiki.write(entry)
            wiki.write(' -> ')
            wiki.write(note)
            wiki.write('\n')            
        except Exception as err:
            print "No note found for", err
            wiki.write(entry)
            wiki.write('\n')

        if details == 'y':
            authors = bib_data.entries[paper].fields['author']
            authors = format_authors(authors)
            authors = '   + ' + ' and '.join(authors)

            try:
                published = '   + ' + bib_data.entries[paper].fields['journal']
            except:
                published = '   + ' + bib_data.entries[paper].fields['booktitle']

            year = '   + ' + bib_data.entries[paper].fields['year']
            
            wiki.write(authors)
            wiki.write('\n')
            wiki.write(published)
            wiki.write('\n')
            wiki.write(year)
            wiki.write('\n')
            
    except Exception as err:
        print "An error occured while processing: ", paper
        print err

wiki.close()


