#!/usr/bin/python
import os
import readline

ext = raw_input("Enter extension (default all): ")
lim = raw_input("Enter delimiter (default - ): ")
parts = raw_input("Enter parts of name to keep (default 2): ")

if lim == '':
    lim = '-'
    
if parts == '':
    parts = 2
else:
    parts = int(parts)

for filename in os.listdir(os.getcwd()):
    if filename.find(ext) != -1:
        fname_list = filename.replace(ext, '').split(lim)
        fname_list = fname_list[:parts]
        new_fname = lim.join(fname_list) + ext
        print new_fname
        os.system('mv ' + filename + ' ' + new_fname)
